# Site settings
title: My Website
author:
  name: Jen wall
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
theme: jekyll-theme-minimal #jekyll/minima remote_
