# Site settings
title: Jen Wallace
author:
  name: Jennifer Wallace
  email: jennifer.2.wallace@uconn.edu
description: "My personal website"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1" #jekyll/minima@d4d779a 

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-seo-tag

minimal_mistakes_skin : "dark"

#minima:
#  skin: solarized-dark

#  nav_pages:
#     - about.md
