# Site settings
title: Jen Wallace
author:
  name: Jennifer Wallace
  email: jennifer.2.wallace@uconn.edu
description: "My personal website"

# Build settings
remote_theme: jekyll/minima@d4d779a #pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-seo-tag

minima:
  skin: dark
